### ISSUE TITLE
extensions option issue if sub-directory with same name

### ISSUE THREAD

**Issue by Felwin** [expressjs/serve-static#108] opened 2018-05-25 05:30 UTC
Using the `extensions` option as such :

    app.use(express.static(__dirname + '/public', { extensions: 'html' }))

I got an issue when there is a file with same name as a folder.
Let's consider this file tree : 

    foo.html
    bar.html
    bar/baz.html

`/foo` will serve `foo.html` and `/bar/baz` will serve `bar/baz.html` as expected, but `/bar` will redirect to `/bar/` 
That make sense because by default serve-static will redirect when a folder is found.
But when I deactivate the redirect as such : 

    app.use(express.static(__dirname + '/public', { extensions: 'html', redirect: false }))

In that case `/bar/baz` will still not serve `bar.html`, it will just move to next()
I believe in this scenario it should serve `bar.html`

Am I missing something here ? To achieve that I did it manually but I believe serve-static should be able to do that.

**Comment by dougwilson** [comment] 2018-05-25 16:45
This is currently the intended behavior: if the URL matches something on the file system no more searching is done on the file system. Since /bar matches a folder /bar the fs resolution is completed as the result was a file. The extensions control how the search works, to continue to look if nothing was found.

The redirect just controls the behavior when the above search completed on a folder (redirect or do nothing to let something else down the line process the folder).

I recall discussions when this was added that both are valid, but only one behavior landed. Maybe an option can be added to enable behavior you're thinking of?

**Comment by recockerell** [comment] 2018-06-08 17:12
※ IAMGCPrd_1528164254109_99999-0703364390.999 this just came across my screen???

**Closed** 2018-06-08 17:22 UTC

**Comment by Felwin** [comment] 2018-06-08 18:07
Thank you for your answer, I understand the actual behavior. 
I believe an option to enable the behavior I described would be nice. 
If I found some time I'll try to propose a way to do that.

**Comment by leviwheatcroft** [comment] 2019-04-15 11:28
I would find an option like this helpful.

Looking at the code, this might be better handled by the [send](https://github.com/pillarjs/send) dependency, because that's responsible for reading from the fs. 

You could achieve the desired behaviour by adding something to the `directory` listenres, but it would be non-trivial, and would require additional dependencies for this package.
